name: ci-autoGreen

on:
  push:
    branches:
      - master
  schedule:
    - cron: "11 */2 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      USERNAME: ${{ secrets.USERNAME }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "${EMAIL}"
          git config --local user.name "${USERNAME}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase

          echo "## AutoGreen" > README.md
          echo "🎾 Last updated: $(TZ=Asia/Singapore date '+%Y-%m-%d %H:%M:%S %Z')" >> README.md
          git add README.md

          git commit --allow-empty -m "a commit a day keeps your girlfriend away..."
          git push
